### PR TITLE
[BUG-70811] adding default blue print for druid bi

### PR DESCRIPTION
**Pull request by b-slim**

### CODE REVIEW

**Comment by martonsereg** [comment]
I've found 2 minor issues with this blueprint:
- METRICS_MONITOR is listed two times in the "worker" hostgroup
- HDFS_CLIENT is only there in the master hostgroup in the other default blueprints, we should keep that convention if possible

Also I'm not familiar with Druid's architecture but it doesn't seem good that the DRUID_MIDDLEMANAGER component is only there in the "compute" hostgroup, because it is possible in HDC that the compute hostgroup doesn't contain nodes at all - it is basically a "worker" group without the Datanode component.

And do we need all these configurations? We'd like to keep these blueprints as simple as possible so if some of these have reasonable default values it would be better.

**Comment by martonsereg** [comment]
Also I've got this error when trying it out:
Cluster Topology validation failed.  Invalid service component count: [DRUID_ROUTER(actual=0, required=1+)]
Do we need to add the DRUID_ROUTER component as well?

**Comment by b-slim** [comment]
@martonsereg thanks 
We actually don't need a router not sure why you get that error ? is it ambari validation ? if it is the case i can always add a router as master node it does not hurt.
also we don't expect ppls to use always MIDDLEMANAGER that's why i have add it as compute.
i will trim the configs as much as possible.

**Comment by b-slim** [comment]
@martonsereg please check this out.

**Comment by martonsereg** [comment]
I'll merge it now, we'll test it from HDC and will change it later if needed.

**Pull request merged**
