### PR TITLE
CLOUD-68853 Polish stack repair flow

### PR DESCRIPTION
**Pull request by mhmxs**
@yhemanth plz review

### CODE REVIEW

**Comment by mhmxs** [comment]
Hi @yhemanth, I haven't time to review you [change](https://github.com/sequenceiq/cloudbreak/pull/2045), but polished some stuff in it. Please review them.

**Comment by yhemanth** [comment]
Just one question, for my understanding. In StackRepairNotificationRequest, I was storing the Stack instance directly. From your changes, it appears such objects should be instead referred by their IDs and pulled up in the handlers. Is the convention to keep the Request objects decoupled from the actual domain?

**Comment by mhmxs** [comment]
Hi @yhemanth,

You are right. We try to avoid states in requests.

**Comment by yhemanth** [comment]
@mhmxs thanks for the response. Is the process for me to merge this into master? I've not done that yet so far on the Cloudbreak project - so checking (not sure if I even have the rights). If you can merge, that's fine by me too - whatever works.

**Pull request merged**
